export interface CommandCatalogItem {
  name: string;
  aliases: string[];
  category: string;
  description: string;
  usage: string;
  dangerLevel: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  defaultRoleProfile: string;
  requiredDiscordPerm?: string;
}

export const BOT_COMMAND_CATALOG: CommandCatalogItem[] = [
  // Moderation
  {
    name: 'purge',
    aliases: ['clear', 'clean', 'purgerole'],
    category: 'moderation',
    description: 'Bulk delete messages from channel or from users with a specific role.',
    usage: '!purge <count> or !purge @role <count>',
    dangerLevel: 'HIGH',
    defaultRoleProfile: 'moderator',
    requiredDiscordPerm: 'Manage Messages',
  },
  {
    name: 'nuke',
    aliases: ['channelnuke', 'clearchannel'],
    category: 'moderation',
    description: 'Deletes and recreates the channel with identical permissions to wipe all chat history.',
    usage: '!nuke',
    dangerLevel: 'CRITICAL',
    defaultRoleProfile: 'administrator',
    requiredDiscordPerm: 'Manage Channels',
  },
  {
    name: 'ban',
    aliases: ['b', 'forceban'],
    category: 'moderation',
    description: 'Permanently ban a member from the server.',
    usage: '!ban @user [reason]',
    dangerLevel: 'CRITICAL',
    defaultRoleProfile: 'administrator',
    requiredDiscordPerm: 'Ban Members',
  },
  {
    name: 'kick',
    aliases: ['k'],
    category: 'moderation',
    description: 'Kick a member from the server.',
    usage: '!kick @user [reason]',
    dangerLevel: 'HIGH',
    defaultRoleProfile: 'moderator',
    requiredDiscordPerm: 'Kick Members',
  },
  {
    name: 'mute',
    aliases: ['timeout', 'shutup'],
    category: 'moderation',
    description: 'Timeout a member for a specified duration.',
    usage: '!mute @user <10m/1h/1d> [reason]',
    dangerLevel: 'MEDIUM',
    defaultRoleProfile: 'moderator',
    requiredDiscordPerm: 'Moderate Members',
  },
  {
    name: 'unmute',
    aliases: ['untimeout'],
    category: 'moderation',
    description: 'Remove timeout from a member.',
    usage: '!unmute @user',
    dangerLevel: 'LOW',
    defaultRoleProfile: 'moderator',
    requiredDiscordPerm: 'Moderate Members',
  },
  {
    name: 'lock',
    aliases: ['lockchannel'],
    category: 'moderation',
    description: 'Lock a text channel to prevent members from sending messages.',
    usage: '!lock [#channel]',
    dangerLevel: 'MEDIUM',
    defaultRoleProfile: 'moderator',
    requiredDiscordPerm: 'Manage Channels',
  },
  {
    name: 'unlock',
    aliases: ['unlockchannel'],
    category: 'moderation',
    description: 'Unlock a text channel to allow member chatting.',
    usage: '!unlock [#channel]',
    dangerLevel: 'LOW',
    defaultRoleProfile: 'moderator',
    requiredDiscordPerm: 'Manage Channels',
  },
  {
    name: 'addrole',
    aliases: ['roleadd', 'giverole'],
    category: 'moderation',
    description: 'Assign a role to a member.',
    usage: '!addrole @user @role',
    dangerLevel: 'MEDIUM',
    defaultRoleProfile: 'moderator',
    requiredDiscordPerm: 'Manage Roles',
  },
  {
    name: 'removerole',
    aliases: ['roledel', 'takerole'],
    category: 'moderation',
    description: 'Remove a role from a member.',
    usage: '!removerole @user @role',
    dangerLevel: 'MEDIUM',
    defaultRoleProfile: 'moderator',
    requiredDiscordPerm: 'Manage Roles',
  },

  // Voice & PVC
  {
    name: 'rw',
    aliases: ['rename', 'vcrename'],
    category: 'voice',
    description: 'Rename private voice channel room.',
    usage: '!rw <new name>',
    dangerLevel: 'LOW',
    defaultRoleProfile: 'viewer',
  },
  {
    name: 'vc',
    aliases: ['vclock', 'vcunlock', 'vchide', 'vcunhide'],
    category: 'voice',
    description: 'Manage private voice channel permissions and lock state.',
    usage: '!vc <lock|unlock|hide|unhide>',
    dangerLevel: 'LOW',
    defaultRoleProfile: 'viewer',
  },
  {
    name: 'move',
    aliases: ['mv', 'vcmove'],
    category: 'voice',
    description: 'Move members to a target voice channel.',
    usage: '!move @user #voice-channel',
    dangerLevel: 'MEDIUM',
    defaultRoleProfile: 'moderator',
    requiredDiscordPerm: 'Move Members',
  },

  // Economy & Store
  {
    name: 'bal',
    aliases: ['balance', 'wallet', 'cash'],
    category: 'economy',
    description: 'Display your or another user\'s current wallet balance and bank holdings.',
    usage: '!bal [@user]',
    dangerLevel: 'LOW',
    defaultRoleProfile: 'viewer',
  },
  {
    name: 'daily',
    aliases: ['claim', 'reward'],
    category: 'economy',
    description: 'Claim your daily currency allowance and streak multiplier.',
    usage: '!daily',
    dangerLevel: 'LOW',
    defaultRoleProfile: 'viewer',
  },
  {
    name: 'give',
    aliases: ['pay', 'transfer'],
    category: 'economy',
    description: 'Transfer cash from your balance to another member.',
    usage: '!give @user <amount>',
    dangerLevel: 'LOW',
    defaultRoleProfile: 'viewer',
  },
  {
    name: 'store',
    aliases: ['shop', 'market'],
    category: 'economy',
    description: 'View the server store catalog.',
    usage: '!store',
    dangerLevel: 'LOW',
    defaultRoleProfile: 'viewer',
  },
  {
    name: 'buy',
    aliases: ['purchase'],
    category: 'economy',
    description: 'Purchase an item or role from the server store.',
    usage: '!buy <item_id>',
    dangerLevel: 'LOW',
    defaultRoleProfile: 'viewer',
  },
  {
    name: 'adminpay',
    aliases: ['givemoney', 'addcash'],
    category: 'economy',
    description: 'Mint currency directly into a member\'s balance.',
    usage: '!adminpay @user <amount>',
    dangerLevel: 'CRITICAL',
    defaultRoleProfile: 'administrator',
  },

  // General & Utility
  {
    name: 'help',
    aliases: ['commands', 'cmds'],
    category: 'general',
    description: 'View interactive help menu and command categories.',
    usage: '!help [category|command]',
    dangerLevel: 'LOW',
    defaultRoleProfile: 'viewer',
  },
  {
    name: 'ping',
    aliases: ['latency', 'status'],
    category: 'general',
    description: 'Check bot gateway latency and REST response time.',
    usage: '!ping',
    dangerLevel: 'LOW',
    defaultRoleProfile: 'viewer',
  },
  {
    name: 'info',
    aliases: ['about', 'stats'],
    category: 'general',
    description: 'Display server information and bot runtime statistics.',
    usage: '!info',
    dangerLevel: 'LOW',
    defaultRoleProfile: 'viewer',
  },
  {
    name: 'sticky',
    aliases: ['stickymessage', 'stickypost'],
    category: 'community',
    description: 'Set persistent sticky notice at bottom of channel.',
    usage: '!sticky <message>',
    dangerLevel: 'MEDIUM',
    defaultRoleProfile: 'moderator',
  },
];
