services:
  - type: web
    name: hawk-discord-bot
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DEV_WEBHOOK_URL
        sync: false
      - key: MAIN_GUILD_ID
        sync: false
      - key: TEST_GUILD_ID
        sync: false
      - key: EMOJI_GUILD_ID
        sync: false
      - key: BOT_OWNER_ID
        sync: false
      - key: BOT_ADMIN_IDS
        sync: false
