/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./hooks/**/*.{js,ts,jsx,tsx,mdx}",
    "./context/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
    "./web/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./web/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./web/hooks/**/*.{js,ts,jsx,tsx,mdx}",
    "./web/context/**/*.{js,ts,jsx,tsx,mdx}",
    "./web/lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: 'rgb(var(--background-rgb) / <alpha-value>)',
        foreground: 'rgb(var(--foreground-rgb) / <alpha-value>)',
        canvas: 'rgb(var(--canvas-rgb) / <alpha-value>)',
        accent: { DEFAULT: '#6366f1', light: '#818cf8', dark: '#4f46e5', muted: 'rgb(99 102 241 / .1)' },
        sidebar: { DEFAULT: 'rgb(var(--sidebar-bg-rgb) / <alpha-value>)', hover: 'rgb(var(--sidebar-hover-bg-rgb) / <alpha-value>)', active: 'rgb(var(--sidebar-active-bg-rgb) / <alpha-value>)', border: 'rgb(var(--border-panel-rgb) / <alpha-value>)' },
        panel: { DEFAULT: 'rgb(var(--surface-panel-rgb) / <alpha-value>)', elevated: 'rgb(var(--surface-elevated-rgb) / <alpha-value>)', surface: 'rgb(var(--surface-card-rgb) / <alpha-value>)', border: 'rgb(var(--border-panel-rgb) / <alpha-value>)', 'border-strong': 'rgb(var(--border-strong-rgb) / <alpha-value>)' },
        surface: Object.fromEntries(Array.from({ length: 6 }, (_, i) => [i, `rgb(var(--surface-${i}-rgb) / <alpha-value>)`])),
        'surface-light': { 0: '#f8f9fc', 1: '#ffffff', 2: '#f1f3f9', 3: '#e8ebf2', 4: '#dfe3ed', 5: '#d5d9e6' },
        border: { DEFAULT: 'rgb(var(--border-panel-rgb) / <alpha-value>)', subtle: 'rgb(var(--border-subtle-rgb) / <alpha-value>)', strong: 'rgb(var(--border-strong-rgb) / <alpha-value>)', focus: 'rgb(var(--accent-rgb) / <alpha-value>)' },
        text: { primary: 'rgb(var(--text-primary-rgb) / <alpha-value>)', secondary: 'rgb(var(--text-secondary-rgb) / <alpha-value>)', muted: 'rgb(var(--text-muted-rgb) / <alpha-value>)', tertiary: 'rgb(var(--text-muted-rgb) / <alpha-value>)', dim: 'rgb(var(--text-muted-rgb) / <alpha-value>)', inverse: '#0f172a' },
        status: { success: '#22c55e', online: '#22c55e', active: '#22c55e', warning: '#f59e0b', critical: '#ef4444', info: '#3b82f6' },
        ...Object.fromEntries(['success','warning','critical','info'].map(name => [name, { DEFAULT: `rgb(var(--status-${name}-rgb) / <alpha-value>)`, text: `rgb(var(--status-${name}-text-rgb) / <alpha-value>)`, soft: `rgb(var(--status-${name}-soft-rgb) / <alpha-value>)`, border: `rgb(var(--status-${name}-border-rgb) / <alpha-value>)` }])),
        console: { bg: 'rgb(var(--console-bg-rgb) / <alpha-value>)', readv: 'rgb(var(--text-primary-rgb) / <alpha-value>)', welcome: 'rgb(var(--status-info-text-rgb) / <alpha-value>)', economy: 'rgb(var(--status-warning-text-rgb) / <alpha-value>)', voice: '#c084fc', store: '#f472b6', community: '#22d3ee', lfg: '#fb923c' },
        discord: { chat: '#313338', sidebar: '#2b2d31', dark: '#1e1f22', embed: '#2b2d31', text: '#dbdee1', muted: '#949ba4', tag: '#5865f2', blurple: '#5865f2' },
      },
      borderRadius: {
        xs: "4px",
        sm: "6px",
        md: "8px",
        lg: "12px",
        xl: "16px",
      },
      boxShadow: {
        'tactile-btn': '0 1px 2px rgba(0,0,0,0.4), inset 0 1px 0 rgba(255,255,255,0.06)',
        'tactile-btn-pressed': '0 0 1px rgba(0,0,0,0.6), inset 0 1px 2px rgba(0,0,0,0.45)',
        'tactile-input': 'inset 0 1px 2px rgba(0,0,0,0.5), 0 1px 0 rgba(255,255,255,0.02)',
        'popover-clean': '0 10px 30px rgba(0,0,0,0.65), 0 0 0 1px rgba(255,255,255,0.05)',
        'drawer-clean': '-10px 0 35px rgba(0,0,0,0.6), 0 0 0 1px rgba(255,255,255,0.04)',
      },
      fontFamily: {
        sans: [
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "Roboto",
          '"Helvetica Neue"',
          "Arial",
          "sans-serif",
        ],
        display: [
          "Bahnschrift",
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "sans-serif",
        ],
        mono: [
          "Cascadia Code",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          '"Liberation Mono"',
          '"Courier New"',
          "monospace",
        ],
      },
    },
  },
  plugins: [],
};
