'use client';
import React, { useEffect, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import { AnimatePresence, motion } from 'framer-motion';
import { Shield, ArrowRight, Sun, Moon, Loader2 } from 'lucide-react';
import { apiFetch } from '@/lib/api';
import { useTheme } from '@/context/ThemeContext';
import { pageVariants } from '@/lib/motion';
export default function LoginPage() {
  const router = useRouter(); const { resolvedTheme, toggleTheme } = useTheme();
  const [step, setStep] = useState<'id' | 'otp'>('id'); const [userId, setUserId] = useState(''); const [digits, setDigits] = useState(Array<string>(6).fill(''));
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [expires, setExpires] = useState(0); const [resendAt, setResendAt] = useState(0); const [now, setNow] = useState(Date.now()); const boxes = useRef<(HTMLInputElement | null)[]>([]);
  useEffect(() => { let alive = true; apiFetch('/api/auth/me').then(r => r.json()).then(data => { if (alive && data.authenticated) router.replace('/dashboard'); }).catch(() => {}); return () => { alive = false; }; }, [router]);
  useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, []);
  const remaining = Math.max(0, Math.ceil((expires - now) / 1000)); const cooldown = Math.max(0, Math.ceil((resendAt - now) / 1000));
  const request = async (event?: React.FormEvent) => {
    event?.preventDefault(); if (busy) return;
    if (!/^\d{17,20}$/.test(userId.trim())) { setError('Enter your 17–20 digit Discord User ID.'); return; }
    setBusy(true); setError(null);
    try { const response = await apiFetch('/api/auth/otp/request', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ userId: userId.trim() }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); const time = Date.now(); setExpires(time + (data.expiresInSeconds || 120) * 1000); setResendAt(time + 30000); setNow(time); setDigits(Array<string>(6).fill('')); setStep('otp'); }
    catch (err) { setError(err instanceof Error ? err.message : 'Could not send a code.'); } finally { setBusy(false); }
  };
  const verify = async (event: React.FormEvent) => { event.preventDefault(); if (busy || !remaining) return; setBusy(true); setError(null); try { const response = await apiFetch('/api/auth/otp/verify', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ userId, otp: digits.join('') }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); router.replace('/dashboard'); router.refresh(); } catch (err) { setError(err instanceof Error ? err.message : 'Could not verify the code.'); } finally { setBusy(false); } };
  const enter = (index: number, input: string) => { const clean = input.replace(/\D/g, '').slice(0, 6); const next = [...digits]; if (!clean) next[index] = ''; else { for (let j = 0; j < clean.length && index + j < 6; j++) next[index + j] = clean[j]; } setDigits(next); if (clean) boxes.current[Math.min(5, index + clean.length)]?.focus(); };
  return <main className="min-h-dvh bg-surface-0 flex flex-col"><header className="px-6 py-5 flex justify-between items-center"><span className="font-display font-semibold text-lg">Hawk <span className="ml-2 text-text-muted font-sans text-xs">Dashboard</span></span><button className="btn-ghost" onClick={toggleTheme} aria-label="Toggle theme">{resolvedTheme === 'dark' ? <Sun size={18}/> : <Moon size={18}/>}</button></header><div className="flex-1 grid place-items-center px-5 py-12"><section className="w-full max-w-md"><div className="w-12 h-12 bg-accent/10 text-accent-light rounded-xl grid place-items-center mb-7"><Shield size={24}/></div><h1 className="text-3xl font-semibold tracking-tight">Your server. In focus.</h1><p className="mt-3 text-text-secondary leading-relaxed text-sm">Sign in through Discord to manage Hawk and see what is happening in your community.</p><div className="surface-container mt-8 p-6"><AnimatePresence mode="wait"><motion.div key={step} variants={pageVariants} initial="initial" animate="enter" exit="exit">
  {step === 'id' ? <form onSubmit={request} className="space-y-5"><div><label htmlFor="discord-id" className="text-sm font-medium">Discord User ID</label><input id="discord-id" className="glass-input mt-2 font-mono" inputMode="numeric" autoComplete="username" required maxLength={20} aria-describedby="id-help" value={userId} onChange={e => setUserId(e.target.value)} disabled={busy}/><p id="id-help" className="text-xs text-text-muted mt-3 leading-relaxed">In Discord, enable Developer Mode in Settings → Advanced, then right-click your profile and choose Copy User ID.</p></div><button className="btn-primary w-full gap-2" disabled={busy}>{busy ? <Loader2 size={16} className="animate-spin"/> : <ArrowRight size={16}/>}Send a code to my DMs</button></form> : <form onSubmit={verify} className="space-y-5"><div className="flex justify-between items-center"><h2 className="text-sm font-medium">Check your Discord DMs</h2><button type="button" disabled={busy} className="btn-ghost" onClick={() => { setStep('id'); setError(null); }}>Change ID</button></div><div className="flex gap-2" role="group" aria-label="Six digit verification code">{digits.map((digit, index) => <input key={index} ref={el => { boxes.current[index] = el; }} aria-label={`Verification digit ${index + 1}`} inputMode="numeric" autoComplete={index === 0 ? 'one-time-code' : 'off'} autoFocus={index === 0} className="glass-input text-center font-mono text-xl px-0 min-w-0" value={digit} disabled={busy} onChange={e => enter(index, e.target.value)} onPaste={e => { e.preventDefault(); enter(index, e.clipboardData.getData('text')); }} onKeyDown={e => { if (e.key === 'Backspace' && !digit && index > 0) boxes.current[index - 1]?.focus(); if (e.key === 'ArrowLeft') boxes.current[Math.max(0, index - 1)]?.focus(); if (e.key === 'ArrowRight') boxes.current[Math.min(5, index + 1)]?.focus(); }}/>)}</div><p className="text-xs text-text-muted">{remaining ? `Code expires in ${Math.floor(remaining / 60)}:${String(remaining % 60).padStart(2, '0')}` : 'This code has expired. Request a new code.'}</p><button className="btn-primary w-full" disabled={busy || !remaining || digits.join('').length !== 6}>{busy ? 'Verifying…' : 'Open dashboard'}</button><button className="btn-ghost w-full" type="button" disabled={busy || cooldown > 0} onClick={() => request()}>{cooldown ? `Resend in ${cooldown}s` : 'Resend code'}</button></form>}
  </motion.div></AnimatePresence>{error && <p role="alert" className="mt-5 text-sm text-critical-text">{error}</p>}</div><p className="text-xs text-text-muted mt-5">Server admins can view. Allowlisted editors can change settings.</p></section></div><footer className="px-6 py-4 text-xs text-text-muted">Hawk · Discord operations</footer></main>;
}
