ALTER TABLE afk_users ADD COLUMN IF NOT EXISTS nickname_set BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE afk_users ADD COLUMN IF NOT EXISTS original_nickname TEXT;
ALTER TABLE afk_users ADD COLUMN IF NOT EXISTS afk_nickname TEXT;
